# -*- coding: utf-8 -*-
"""Breast Cancer Neural Net.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fcrTKUbSJdOHtGvtVFj5l9l01G9FZamX

**Imports**
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from tensorflow.keras.models import Sequential
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam
from keras.layers import Activation, Dense

from google.colab import drive

"""**Mounting Google Drive**"""

drive.mount('/content/drive')

"""**Processing Data**"""

dataset = pd.read_csv('/content/drive/MyDrive/Breast Cancer Dataset/data.csv')
labels = dataset.iloc[:, -1]
features = dataset.iloc[:, 0:-1]
features = pd.get_dummies(features)
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.20, random_state = 100)

"""**Normalizing Data**"""

numerical_features = features.select_dtypes(include=['float64', 'int64'])
numerical_columns = numerical_features.columns

ct = ColumnTransformer([("normalize", Normalizer(), numerical_columns)], remainder = 'passthrough')

features_train_scaled = ct.fit_transform(features_train)
features_test_scaled = ct.fit_transform(features_test)

"""**Creating the Model**"""

model = tf.keras.models.Sequential() # create network structure
model.add(Dense(10, input_shape = features.shape[1:], activation ='relu'))
model.summary()

"""**Optimizing and Compiling**"""

opt = Adam(learning_rate = 0.01)
model.compile(loss = 'mse', metrics = ['mae'], optimizer = opt)

model.fit(features_train_scaled, labels_train, epochs = 100, batch_size = 1, verbose = 1)
res_mse, res_mae = model.evaluate(features_test_scaled, labels_test, verbose = 0)

print(res_mse, res_mae)